apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadium-api-server
spec:
  replicas: {{ .Values.apiServer.replicaCount }}
  selector:
    matchLabels:
      app: arcadium-api-server
  template:
    metadata:
      labels:
        app: arcadium-api-server
    spec:
      containers:
        - name: app
          image: {{ .Values.apiServer.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /api/actuator/health
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /api/actuator/health
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.apiServer.resources | nindent 12 }}
