apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: session-server-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: session-server-role
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: session-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: session-server-role
subjects:
  - kind: ServiceAccount
    name: session-server-serviceaccount
    namespace: default
