apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadium-transport
spec:
  replicas: {{ .Values.transport.replicaCount }}
  selector:
    matchLabels:
      app: arcadium-transport
  template:
    metadata:
      labels:
        app: arcadium-transport
    spec:
      containers:
        - name: app
          image: {{ .Values.transport.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /transport/actuator/health
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /transport/actuator/health
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.transport.resources | nindent 12 }}
