apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadium-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: arcadium-web
  template:
    metadata:
      labels:
        app: arcadium-web
    spec:
      containers:
        - name: app
          image: {{ .Values.web.image }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
              path: /
          readinessProbe:
            httpGet:
              port: 80
              path: /
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
